auth_enabled: false

server:
  http_listen_port: 3100
  grpc_listen_port: 9096

common:
  path_prefix: ./
  storage:
    filesystem:
      chunks_directory: ./chunks
      rules_directory: ./rules
  replication_factor: 1
  ring:
    instance_addr: 127.0.0.1
    # kvstore:
    #   store: inmemory

# cassandra to keep the index
schema_config:
  configs:
  - from: 2020-05-15
    store: cassandra
    object_store: filesystem
    schema: v11
    index:
      prefix: cassandra_table
      period: 24h

storage_config:
  cassandra:
    username: cassandra
    password: cassandra
    addresses: 127.0.0.1
    auth: true
    keyspace: lokiindex

# file system config
# schema_config:
#   configs:
#     - from: 2020-10-24
#       store: boltdb-shipper
#       object_store: filesystem
#       schema: v11
#       index:
#         prefix: index_
#         period: 24h

ruler:
  alertmanager_url: http://localhost:9093

limits_config:
  max_streams_per_user: 10000