server:
  http_listen_port: 9080
  grpc_listen_port: 0

positions:
  filename: ./positions.yaml

clients:
  - url: http://localhost:3100/loki/api/v1/push

scrape_configs:
- job_name: yb_master_n1
  pipeline_stages:
  - regex:
      expression: ^\\s*(?P<level>\\w)(?P<date>\\d{2}\\d{2})\\s(?P<timestamp>\\d{2}:\\d{2}:\\d{2}\\.\\d{6})\\s(?P<id>\\d+)\\s(?P<file>.+):(?P<line>\\d+)\\]\\s(?P<message>.*?)\\s*$
  # - labels:
  #     level:
  static_configs:
  - targets:
      - localhost
    labels:
      export_type: "master_export"
      job: yb_master_n1
      __path__: ${YB_STORE}/ybdb/ybd1/logs/master/yb-master.*log*
- job_name: yb_tserver_n1
  pipeline_stages:
  - regex:
      expression: ^\\s*(?P<level>\\w)(?P<date>\\d{2}\\d{2})\\s(?P<timestamp>\\d{2}:\\d{2}:\\d{2}\\.\\d{6})\\s(?P<id>\\d+)\\s(?P<file>.+):(?P<line>\\d+)\\]\\s(?P<message>.*?)\\s*$
  # - labels:
  #     level:
  static_configs:
  - targets:
      - localhost
    labels:
      export_type: "tserver_export"
      job: yb_tserver_n1
      __path__: ${YB_STORE}/ybdb/ybd1/logs/tserver/yb-tserver.*log*
- job_name: yb_postgres_n1
  static_configs:
  - targets:
      - localhost
    labels:
      export_type: "postgres_export"
      job: yb_postgres_n1
      __path__: ${YB_STORE}/ybdb/ybd1/logs/tserver/postgres*.log
- job_name: yb_master_n2
  pipeline_stages:
  - regex:
      expression: ^\\s*(?P<level>\\w)(?P<date>\\d{2}\\d{2})\\s(?P<timestamp>\\d{2}:\\d{2}:\\d{2}\\.\\d{6})\\s(?P<id>\\d+)\\s(?P<file>.+):(?P<line>\\d+)\\]\\s(?P<message>.*?)\\s*$
  # - labels:
  #     level:
  static_configs:
  - targets:
      - localhost
    labels:
      export_type: "master_export"
      job: yb_master_n2
      __path__: ${YB_STORE}/ybdb/ybd2/logs/master/yb-master.*log*
- job_name: yb_tserver_n2
  pipeline_stages:
  - regex:
      expression: ^\\s*(?P<level>\\w)(?P<date>\\d{2}\\d{2})\\s(?P<timestamp>\\d{2}:\\d{2}:\\d{2}\\.\\d{6})\\s(?P<id>\\d+)\\s(?P<file>.+):(?P<line>\\d+)\\]\\s(?P<message>.*?)\\s*$
  # - labels:
  #     level:
  static_configs:
  - targets:
      - localhost
    labels:
      export_type: "tserver_export"
      job: yb_tserver_n2
      __path__: ${YB_STORE}/ybdb/ybd2/logs/tserver/yb-tserver.*log*
- job_name: yb_postgres_n2
  static_configs:
  - targets:
      - localhost
    labels:
      export_type: "postgres_export"
      job: yb_postgres_n2
      __path__: ${YB_STORE}/ybdb/ybd2/logs/tserver/postgres*.log
- job_name: yb_master_n3
  pipeline_stages:
  - regex:
      expression: ^\\s*(?P<level>\\w)(?P<date>\\d{2}\\d{2})\\s(?P<timestamp>\\d{2}:\\d{2}:\\d{2}\\.\\d{6})\\s(?P<id>\\d+)\\s(?P<file>.+):(?P<line>\\d+)\\]\\s(?P<message>.*?)\\s*$
  # - labels:
  #     level:
  static_configs:
  - targets:
      - localhost
    labels:
      export_type: "master_export"
      job: yb_master_n3
      __path__: ${YB_STORE}/ybdb/ybd3/logs/master/yb-master.*log*
- job_name: yb_tserver_n3
  pipeline_stages:
  - regex:
      expression: ^\\s*(?P<level>\\w)(?P<date>\\d{2}\\d{2})\\s(?P<timestamp>\\d{2}:\\d{2}:\\d{2}\\.\\d{6})\\s(?P<id>\\d+)\\s(?P<file>.+):(?P<line>\\d+)\\]\\s(?P<message>.*?)\\s*$
  # - labels:
  #     level:
  static_configs:
  - targets:
      - localhost
    labels:
      export_type: "tserver_export"
      job: yb_tserver_n3
      __path__: ${YB_STORE}/ybdb/ybd3/logs/tserver/yb-tserver.*log*
- job_name: yb_postgres_n3
  static_configs:
  - targets:
      - localhost
    labels:
      export_type: "postgres_export"
      job: yb_postgres_n3
      __path__: ${YB_STORE}/ybdb/ybd3/logs/tserver/postgres*.log
